### ISSUE TITLE
QA for Version 1.0.16.3

### ISSUE THREAD

**Issue by amytruong** [github/VisualStudio#208]
Release Notes: https://github.com/github/VisualStudio/releases/tag/v1.0.16.3-beta2
Manifest: https://github.ontestpad.com/script/84#2//

**Comment by amytruong** [comment]
Need to test the following extra cases: 

- [ ] Have latest regular release and update via the custom Gallery 
- [ ] Each release in the custom gallery has a link to the release notes on the right side, and if you hover over the description of each release it will show the release notes as well
- [ ] Testing the signing certificate change is basically going through the upgrade from 1.0.16.2 to 1.0.16.3 and making sure it works

**Comment by shana** [comment]
Just fyi the release notes were missing a bug fix, I've added it now.

**Comment by amytruong** [comment]
@shana 
>- [ ] Each release in the custom gallery has a link to the release notes on the right side, and if you hover over the description of each release it will show the release notes as well

I see the the link to the Release Notes but when you hover over the description of each release (More Information), should I see a tool tip or something?

**Comment by amytruong** [comment]
- [ ] #176 - Dialog window never closes
- [ ] #192 - Crash after publishing repository
- [ ] #202 - Login credentials keep resetting
- [ ] #203 - Clone/Create message is shown before cloning/creating actually runs

**Comment by shana** [comment]
> I see the the link to the Release Notes but when you hover over the description of each release (More Information), should I see a tool tip or something?

Yeah, a tooltip should show up. But don't worry about it too much, it's a detail of the list and not really important. As long as you can get to the release, that's what matters.

**Comment by shana** [comment]
>  #203 - Clone/Create message is shown before cloning/creating actually runs - Not fixed

Damnit! Thanks, I was afraid I might have missed something. Back to the drawing board...

**Comment by amytruong** [comment]
@shana awesome! It's not showing up right now but getting to Releases is easy peasy since it's all linked. :+1: 

For #203: yea :cry: I'm going to update the manifest to include test cases with user with 2FA and a user without because I've missed the 2FA login/dialog window issue! :angry:

**Comment by amytruong** [comment]
Existing bug just to be noted from the test run in #157 
The evilamyt/beer-is-cool (i think it's a link to the repo on .com since the tooltip says

>u:http://github.com/evilamyt/beer-is-cool

**Comment by shana** [comment]
Oh! Regarding the "Connect page was slow to load", that was pissing the hell out of me so I had to fix it. It's hard to know what "slow" is unless you're like me and have zero patience for anything being remotely not realtime in the UI, so don't worry about that one (it's working, I know, I sigh of relief every time it loads fast)

**Comment by shana** [comment]
>  #192 - Crash after publishing repository

Regarding this one, it's a race condition so it's hard to trigger. Does not blow up in your face is a good test :)

**Comment by shana** [comment]
Regarding #203 being partially fixed, I might make a new release build just with the fix for that or I might just ship it partially fixed, so keep going with the rest of the tests while I figure things out (it's not a really critical bug anyway).

**Comment by amytruong** [comment]
Thanks for all the info @shana! 

>- [ ] Notification appears: "Repository published successfully" 

For this case in the manifest, I'm not seeing this message anymore when I publish a repo via the Sync button --> Get Started section. Wonder if I'm the only one? 

Another weird scenario that wasn't covered in the manifest: 
1.Verify you're signed out of GitHub
2. On Team Explorer, click Login
3. Select GitHub Enterprise
4. Enter in all required fields but with an invalid password
5. Login and receive Login Failed message
6. Click on GitHub and enter in required fields correctly 
7. Login 

**Expected Results:** You're logged in and the login box disappears? 
**Actual Results:** The login box displays with GitHub Enterprise section displayed
![screen shot 2016-01-21 at 10 26 04 am](https://cloud.githubusercontent.com/assets/10725993/12488672/f302d1a8-c029-11e5-809b-217cc7e6539e.png)

**Comment by amytruong** [comment]
>- [ ] Click Clone in "Local Git Repositories" List and copy/paste a repo from .com. Clone and verify the message displays, "The repository was cloned successfully."

I noticed that if I don't pick an empty directory, I get the following:
![screen shot 2016-01-21 at 10 40 54 am](https://cloud.githubusercontent.com/assets/10725993/12489012/8454dc18-c02b-11e5-9d97-1720ccac7221.png)
Not sure if it's our issue but a bit annoying since I should be able to pick a non-empty directory

**Comment by shana** [comment]
Yeah, that's bad UI design in VS, I agree. Totally not our issue fortunately (or unfortunately?), "Local Git Repositories" is done by Microsoft.

**Comment by shana** [comment]
> Another weird scenario that wasn't covered in the manifest: 
1.Verify you're signed out of GitHub
2. On Team Explorer, click Login
3. Select GitHub Enterprise
4. Enter in all required fields but with an invalid password
5. Login and receive Login Failed message
6. Click on GitHub and enter in required fields correctly 
7. Login
Expected Results: You're logged in and the login box disappears? 
Actual Results: The login box displays with GitHub Enterprise section displayed

Ah, interesting. One of the bugs was the login dialog not going away, this might be perhaps an edge case related to that bug
