### ISSUE TITLE
Pull Requests v1: Tasks

### ISSUE THREAD

**Issue by shana** [github/VisualStudio#326]
#119 has been merged but there are still things left to do. This issue tracks all tasks for v1 of the Pull Requests feature (#20)
### Tasks
- [x] GitHub pane
  - [x] Navigation
  - [x] Refresh
  - [x] PR button
- [ ] PR list
  - [x] Filtering
  - [x] State
    - [ ] UI
    - [ ] Data
  - [x] Assignee
    - [x] UI
    - [x] Data
  - [x] Author
    - [x] UI
    - [x] Data
  - [ ] PR details in the list view (commit count, etc)
  - [x] Jump to detail on the website
  - [x] Jump to PR creation
- [x] PR creation
  - [x] Target branch list
    - [x] UI
    - [x] Data
  - [x] Source branch
  - [x] Title
  - [x] Description
  - [x] Optional assignee user
    - [x] UI
    - [x] Data
  - [x] Cancel button
  - [x] Refresh button
  - [x] PR creation

**Comment by SeanFeldman** [comment]
Would PR creation, title and description, eventually behave the same way they do on the web? I.e. by default be based on the last commit`s comment?

**Comment by shana** [comment]
@SeanFeldman Yup, we have a separate issue to track that (sorry for the lateness in the response!) #767

**Comment by shana** [comment]
This shipped! 🎉

**Comment by Haacked** [comment]
![](https://cloud.githubusercontent.com/assets/19977/22475811/0a108244-e795-11e6-9dcc-ad3dd549cef3.gif)

**Comment by SeanFeldman** [comment]
@shana congrats.
Better late than never 😃
